data:
    name: 'NeRF_dataset'
    class_name: 'NeRF'
    data_dir: 'Dining'
    experiment_name: 'MP_NeRF_v1/Dining'
    image_size: [480, 640]
    fov: 44
    has_labels: False
    warped_pair: False
    augmentation:
        photometric:
            enable: False
    batch_size: 10
    truncate: False
model:
    script: 'SuperPoint'
    class_name: 'SuperPoint'
    model_name: 'magicpoint'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        nms: 8
        det_thresh: 0.015
        top_k: 0
pretrained: 'magicpoint_syn_v1/magicpoint_syn_v1_200000.pth'