data:
    name: 'NeRF_dataset'
    class_name: 'NeRF'
    all_data_dirs: ['Desk',
                    'Lab',
                    'Graffiti',
                    'Greece_Building',
                    'Paintings',
                    'Malet',
                    'Train',
                    'Art',
                    'Dining',
                    'Kitchen']
    data_dir: ''
    image_size: [480, 640]
    downsample: False
    downsample_size: [240,320]
    fov: 44
    batch_size: 32
    truncate: False
    all_label_dirs: ['outputs/MP_NeRF_v2/Desk',
                     'outputs/MP_NeRF_v2/Lab',
                     'outputs/MP_NeRF_v2/Graffiti',
                     'outputs/MP_NeRF_v2/Greece_Building',
                     'outputs/MP_NeRF_v2/Paintings',
                     'outputs/MP_NeRF_v2/Malet',
                     'outputs/MP_NeRF_v2/Train',
                     'outputs/MP_NeRF_v2/Art',
                     'outputs/MP_NeRF_v2/Dining',
                     'outputs/MP_NeRF_v2/Kitchen']
    has_labels: ''
    warped_pair: False
    augmentation:
        photometric:
            enable: True
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.3, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [150, 200]
                    nb_ellipses: 20
                motion_blur: {max_kernel_size: 3}
model:
    script: 'SuperPoint'
    class_name: 'SuperPoint'
    model_name: 'magicpoint'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        nms: 4
        det_thresh: 0.001
        top_k: 0
train:
    num_iters: 25000
    learning_rate: 0.001
save_or_validation_interval: 1000
ckpt_name: 'MP_NeRF_v2'
pretrained: 'MP_NeRF_v1/MP_NeRF_v1_20000.pth'
continue_training: False