data:
    gt_pairs: 'ScanNet/scannet_test_pairs_with_gt.txt'
    images_path:  'ScanNet'
    resize: [640,480]
    epi_thrsehold: 0.0005
    resize_float: false
model:
    script: 'SuperPoint'
    class_name: 'SuperPoint'
    model_name: 'superpoint'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        det_thresh: 0.001
        nms: 4
        top_k: 1024
    descriptor_head:
        descriptor_dim: [128,256]
        grid_size: 8
pretrained: 'SP_NeRF_v3/SP_NeRF_v3_440000.pth'
