data:
    name: 'HPatches'
    class_name: 'HPatches'
    experiment_name: 'Superpoint_Baseline_nms_4'
    alteration: 'v' #or 'i' 'all' 
    batch_size: 1
    preprocessing:
        resize: [480,640] 
    correctness_thresh: 3
model:
    script: 'SuperPoint'
    class_name: 'SuperPoint'
    model_name: 'superpoint'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        nms: 4
        det_thresh: 0.001
        top_k: 1000
    descriptor_head:
        descriptor_dim: [128,256]
        grid_size: 8
pretrained: 'Superpoint_Baseline/Superpoint_Baseline_420000.pth'
