data:
    name: 'NeRF_dataset'
    class_name: 'NeRF'
    all_data_dirs: ['Desk',
                    'Lab',
                    'Graffiti',
                    'Greece_Building',
                    'Paintings',
                    'Malet',
                    'Train',
                    'Art',
                    'Dining',
                    'Kitchen']
    data_dir: ''
    image_size: [480, 640]
    downsample: False
    downsample_size: [240,320]
    fov: 44
    batch_size: 2
    truncate: False
    all_label_dirs: ['outputs/SP_NeRF_v3/Desk',
                     'outputs/SP_NeRF_v3/Lab',
                     'outputs/SP_NeRF_v3/Graffiti',
                     'outputs/SP_NeRF_v3/Greece_Building',
                     'outputs/SP_NeRF_v3/Paintings',
                     'outputs/SP_NeRF_v3/Malet',
                     'outputs/SP_NeRF_v3/Train',
                     'outputs/SP_NeRF_v3/Art',
                     'outputs/SP_NeRF_v3/Dining',
                     'outputs/SP_NeRF_v3/Kitchen']
    has_labels: ''
    warped_pair: True
    augmentation:
        photometric:
            enable: True
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [150, 200]
                    nb_ellipses: 20
                motion_blur: {max_kernel_size: 3}
model:
    script: 'SuperPoint'
    class_name: 'SuperPoint'
    model_name: 'superpoint'
    vgg_cn: [64,64,64,64,128,128,128,128]
    detector_head: 
        detector_dim: [128,256]
        grid_size: 8
        nms: 4
        det_thresh: 0.001
        top_k: 0
    descriptor_head:
        descriptor_dim: [128,256]
        grid_size: 8
        positive_margin: 1.0
        negative_margin: 0.2
        lambda_d: 250
        lambda_loss: 0.0001
        normalise_descriptors: False
train:
    num_iters: 450000
    learning_rate: 0.001
save_or_validation_interval: 5000
ckpt_name: 'SP_NeRF_v3'
pretrained: 'MP_NeRF_v2/MP_NeRF_v2_25000.pth'
continue_training: False